
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-03T05:33:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a3eb9771cd0af90d0f8c32140313c8be43e5f04",
 "version": "4.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
